
version: 2
jobs:
  build:
    working_directory: ~/software-training
    docker:
      - image: silex/emacs:25.1
    steps:
      # Install cask
      - run: curl -fsSL https://raw.githubusercontent.com/cask/cask/master/go | python
      - checkout
      - run: git config --global user.name "$GIT_USERNAME" && git config --global user.email "$GIT_EMAIL"
      - run: git clone "$CIRCLE_REPOSITORY_URL" html && cd html && git checkout gh-pages && cd ..
      - run:
          name: No HTTP Check
          command: sh -c "! grep -r 'http[^s]' src/"
      - run: ~/.cask/bin/cask install
        # Generate build files to /html
      - run: ~/.cask/bin/cask eval "(progn (require 'rj-software-training) (rj-software-training-publish))"
      - deploy:
          name: Deploy to github
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
            cd html && git add . && git commit -m "Autoupdate html sources" || true && git push https://$GH_TOKEN@github.com/RoboJackets/software-training gh-pages || true
            fi
